"""
Data Schemas and Transfer Objects (DTOs)

Concept Explanation:
--------------------
In modern API engineering, defining strong data contracts between the client and server
prevents runtime errors, enables automatic OpenAPI/Swagger documentation, and validates 
incoming inputs before any business logic is executed.

Here we use Pydantic models to define:
- `ChatMessage`: The atomic structure of a conversation turn (role, content, timestamp).
- `ChatRequest`: The payload sent by the frontend chat client.
- `ChatResponse`: The structured reply from our AI Agent (including metadata like intent and sentiment).
- `SentimentAnalysis`: Quantified emotional assessment of a journal entry or message.
- `HealthStatus`: Telemetry data for Kubernetes / Docker container health checks.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum


class MessageRole(str, Enum):
    """
    Standardized conversation roles.
    Matches industry standards (OpenAI / Gemini chat format).
    """
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class UserIntent(str, Enum):
    """
    Agentic Intent Classification Categories.
    
    Concept:
    Before an AI Agent generates a response, it classifies the user's intent.
    This enables dynamic routing (e.g. triggering crisis protocol vs breathing guide).
    """
    GENERAL = "general"                 # Casual greeting or open-ended dialogue
    VENTING = "venting"                 # Expressing emotions, seeking an empathetic ear
    ANXIETY_STRESS = "anxiety_stress"   # Experiencing high stress, anxiety, panic
    CRISIS_URGENT = "crisis_urgent"     # Severe self-harm, emergency, suicide risk
    COPING_EXERCISE = "coping_exercise" # Asking for breathing/grounding/relaxation techniques
    RELATIONSHIP = "relationship"       # Interpersonal conflict or social loneliness
    WORK_BURNOUT = "work_burnout"       # Workplace fatigue, career pressure


class ChatMessage(BaseModel):
    """
    Represents a single message in a conversation thread.
    """
    id: Optional[str] = Field(default=None, description="Unique client or server message identifier")
    role: MessageRole = Field(..., description="Role of the sender: user, assistant, or system")
    content: str = Field(..., min_length=1, description="Text content of the message")
    timestamp: Optional[int] = Field(default=None, description="Epoch timestamp in milliseconds")


class ChatRequest(BaseModel):
    """
    Incoming request payload for chat completion and streaming endpoints.
    """
    messages: List[ChatMessage] = Field(..., min_length=1, description="Chronological conversation history")
    session_id: Optional[str] = Field(default="anonymous-session", description="Optional session tracking ID")
    stream: bool = Field(default=False, description="Whether to stream tokens via Server-Sent Events (SSE)")
    
    class Config:
        json_schema_extra = {
            "example": {
                "messages": [
                    {"role": "user", "content": "I feel very overwhelmed with work today."}
                ],
                "session_id": "user-session-123",
                "stream": True
            }
        }


class SafetyEvaluation(BaseModel):
    """
    Security & Safety Guardrail assessment result.
    
    Concept:
    In critical domains like SecOps (ReliaQuest) or Mental Health, 
    guardrails act as an automated firewall to catch dangerous or policy-violating input
    before and after model invocation.
    """
    is_safe: bool = Field(default=True, description="True if input passed all safety checks")
    flagged_crisis: bool = Field(default=False, description="True if self-harm / crisis indicators detected")
    flagged_injection: bool = Field(default=False, description="True if prompt injection / jailbreak detected")
    reason: Optional[str] = Field(default=None, description="Explanation if input was flagged")
    recommended_hotline: Optional[str] = Field(default=None, description="Emergency contact info if crisis flagged")


class ChatResponse(BaseModel):
    """
    Outgoing response returned by the MindMate Agent API.
    """
    message: str = Field(..., description="The empathetic response generated by the AI agent")
    intent: UserIntent = Field(default=UserIntent.GENERAL, description="Detected intent of the user")
    safety: SafetyEvaluation = Field(default_factory=SafetyEvaluation, description="Safety and guardrail evaluation")
    sentiment_score: Optional[float] = Field(default=0.0, description="Sentiment score from -1.0 (very negative) to +1.0 (very positive)")
    detected_emotions: List[str] = Field(default_factory=list, description="List of detected emotional states (e.g. anxious, tired)")
    model_used: str = Field(default="gemini-1.5-flash", description="Underlying AI model or fallback engine used")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="UTC timestamp of response generation")


class SentimentAnalysisRequest(BaseModel):
    """
    Request model for analyzing journal entries or standalone texts.
    """
    text: str = Field(..., min_length=1, description="Text to evaluate for emotional sentiment")


class SentimentAnalysisResponse(BaseModel):
    """
    Response model for sentiment and emotion evaluation.
    """
    sentiment: str = Field(..., description="Overall label: positive, neutral, anxious, stressed, sad")
    score: float = Field(..., description="Numerical sentiment score from -1.0 to 1.0")
    primary_emotions: List[str] = Field(default_factory=list, description="Key emotions identified in the text")
    suggested_actions: List[str] = Field(default_factory=list, description="Recommended coping activities or prompts")


class HealthStatus(BaseModel):
    """
    Microservice Health & Readiness Schema.
    
    Used by load balancers and container orchestrators (e.g., Kubernetes/Docker)
    to check service availability and readiness.
    """
    status: str = Field(default="healthy", description="Current service health state")
    service: str = Field(default="mindmate-backend", description="Microservice name")
    version: str = Field(default="1.0.0", description="API version")
    gemini_configured: bool = Field(..., description="Whether Google Gemini API key is configured")
    openai_configured: bool = Field(..., description="Whether OpenAI API key is configured")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Server current UTC timestamp")
